version: "2"
services:
  event-archiver:
    image: rabblerouser/event-archiver
    build: "git@github.com:rabblerouser/event-archiver.git"
    external_links:
      - "s3:rr-event-archive.s3"
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "npm test"
