version: "2"
services:
  kinesis:
    image: instructure/kinesalite
    ports:
      - '4567:4567'
    volumes:
      - ../kinesis-data:/var/lib/kinesalite
  s3:
    image: camjackson/fake-s3
    ports:
      - '4569:4569'
    volumes:
      - ../s3-data:/fakes3_root
  ses:
    image: camjackson/aws-ses-local
    volumes:
      - ../sent-mail:/aws-ses-local/output
  event-archiver:
    # This kinda doesn't belong here, but it needs to be up before the init script runs, so... ¯\_(ツ)_/¯
    image: rabblerouser/event-archiver
    build: "git@github.com:rabblerouser/event-archiver.git"
    external_links:
      - "s3:rr-event-archive.s3"
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "npm test"
