version: "2"
services:
  kinesis:
    image: instructure/kinesalite
  s3:
    image: lphoward/fake-s3
    ports:
      - '4569:4569'
  ses:
    image: camjackson/aws-ses-local
    volumes:
      - ../sent-mail:/aws-ses-local/output
