version: "2"
services:
  core:
    image: rabblerouser/core
    build: "git@github.com:rabblerouser/core.git"
    ports:
      - "3000:3000"
      - "8080:8080"
    external_links:
      - "s3:rr-event-archive.s3"
    environment:
      # PORT: 3000 TODO: This would affect both the backend and frontend, which would cause conflicts.
      # Once we split the backend and frontend into separate containers, they can be portified independently.
      # For now the ports will default to 3000/8080 anyway, so it's OK.
      LISTENER_AUTH_TOKEN: secret
    command: yarn dev
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "yarn test"
  core-event-forwarder:
    image: rabblerouser/event-forwarder
    build: "git@github.com:rabblerouser/event-forwarder.git"
    environment:
      LISTENER_ENDPOINT: http://core:3000/events
      LISTENER_AUTH_TOKEN: secret
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "yarn test"
