version: "2"
services:
  mailer:
    image: rabblerouser/mailer
    build: "git@github.com:rabblerouser/mailer.git"
    ports:
      - "3001:3001"
    environment:
      LISTENER_AUTH_TOKEN: secret
    command: npm run dev
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "npm test"
  mailer-event-forwarder:
    image: rabblerouser/event-forwarder
    build: "git@github.com:rabblerouser/event-forwarder.git"
    environment:
      LISTENER_ENDPOINT: http://mailer:3001/events
      LISTENER_AUTH_TOKEN: secret
    labels:
      io.fdy.cage.srcdir: "/app"
      io.fdy.cage.test: "npm test"
